### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by Readyou123** [Tencent/HunyuanDiT#78]
为什么感觉图片的尺寸越小，效果越差呢？

**Comment by chenbiaolong** [comment]
我也遇到同样的情况，用512x512分辨率得到的图片和几乎是噪声图,有和我一样情况的吗？运行命令
```shell
python sample_t2i.py --prompt "渔舟唱晚" --no-enhance --image-size 512 512
```
![9](https://github.com/Tencent/HunyuanDiT/assets/9475734/b46a9605-e7e0-4355-9aae-6a92e3a150ec)

**Comment by zml-ai** [comment]
HunYuan-v1.0/v1.1 are designed for 1024 resolution. Due to training strategy constraints (silver and gold label data with resolution higher than 1024p), it performs better with resolutions close to 1024p. 

For recommended resolutions, see: https://github.com/Tencent/HunyuanDiT/blob/main/hydit/inference.py#L63. We plan to release models of various resolutions and parameter sizes in the future, stay tuned.

**Comment by JH-Xie** [comment]
> HunYuan-v1.0/v1.1 are designed for 1024 resolution. Due to training strategy constraints (silver and gold label data with resolution higher than 1024p), it performs better with resolutions close to 1024p.
> 
> For recommended resolutions, see: https://github.com/Tencent/HunyuanDiT/blob/main/hydit/inference.py#L63. We plan to release models of various resolutions and parameter sizes in the future, stay tuned.

I have tried generate a 768x1024 image as recommend in https://github.com/Tencent/HunyuanDiT/blob/main/hydit/inference.py#L63. the result image looks well but always  have some mosaic/blur pixel on the bottom of the image(doesn't happen when use 1024x1024). is it a bug?
![Uploading image.png…]()
