### ISSUE TITLE
能否把mt5模型剪枝成多个国家双语版的，尤其是中英双语？

### ISSUE THREAD

**Issue by petercham** [Tencent/HunyuanDiT#89]
现在的mt5模型实在太大了

**Comment by zml-ai** [comment]
Thank you for your interest in our product. Pruning typically reduces a model’s size by eliminating specific structures or redundant neurons. However, MT5’s design, which uses a unified encoder for all languages, means that pruning would affect its performance across all languages due to its shared parameters. 
Therefore, creating specific bilingual models by pruning isn’t feasible. If VRAM limitations are an issue for inference, we suggest trying the VRAM-optimized code we plan to release soon.
